MATCHES = "matches"
MATCHES_MATCH_ID = "match_id"
MATCHES_TEAM1 = "team1"
MATCHES_TEAM2 = "team2"
MATCHES_SOFASCORE_LINK = "sofascore_link"
MATCHES_SCRAPED = "scraped"
MATCHES_TEAM1_SCORE = "team2_score"
MATCHES_TEAM2_SCORE = "team2_score"
MATCHES_MATCH_DATE = "match_date"
MATCHES_STADIUM = "stadium"
MATCHES_STADIUM_LOCATION = "stadium_location"

STATS = "stats"
STATS_PLAYER_NAME = "player_name"
STATS_PLAYER_ID = "player_id"
STATS_MATCH_ID = "match_id"